library(tidyverse)

# To make a longer table from a wider table of seqtab table generated by DADA2
seqtab <- as.data.frame(readRDS("seqtab_final.rds"))
asv_table <- seqtab %>%   
  mutate(sample = rownames(seqtab)) %>% 
  pivot_longer(-sample, names_to = "asv", values_to = "count") %>% 
  glimpse()

# Join the taxonomic information and metadata into the table  
tax_spec <- as.data.frame(readRDS("tax_final.rds"))
l_tax <- vector()
for (i in rownames(tax_spec)) {
  if (!is.na(tax_spec[i,7])) {
    l_tax <- append(l_tax,paste("s__",tax_spec[i,6]," ",tax_spec[i,7],sep=""))
  } else if (!is.na(tax_spec[i,6])) {
    l_tax <- append(l_tax,paste("g",tax_spec[i,6],sep="__"))
  } else if (!is.na(tax_spec[i,5])) {
    l_tax <- append(l_tax,paste("f",tax_spec[i,5],sep="__"))
  } else if (!is.na(tax_spec[i,4])) {
    l_tax <- append(l_tax,paste("o",tax_spec[i,4],sep="__"))
  } else if (!is.na(tax_spec[i,3])) {
    l_tax <- append(l_tax,paste("c",tax_spec[i,3],sep="__"))
  } else if (!is.na(tax_spec[i,2])) {
    l_tax <- append(l_tax,paste("p",tax_spec[i,2],sep="__"))
  } else if (!is.na(tax_spec[i,1])) {
    l_tax <- append(l_tax,paste("k",tax_spec[i,1],sep="__"))
  } else {
    l_tax <- append(l_tax,"__")
  }
}

tax_table <- data.frame(asv = rownames(tax_spec), taxa = l_tax) %>% glimpse()
metadata <- read_csv("Metadata.csv") %>% 
  dplyr::rename(sample = sample_name) %>% glimpse()

comb_table <- inner_join(asv_table, tax_table, by = "asv") %>% 
  inner_join(., metadata, by = "sample") %>% 
  select(-forward_name,-reverse_name) %>% 
  glimpse()

f.table <- comb_table %>% 
  group_by(sample) %>% 
  # 1. Filter low sequencing dept
  filter(sum(count) > 2500) %>% 
  group_by(metabolite) %>% 
  mutate(rep = n_distinct(sample)) %>%
  filter(rep >= 3) %>% 
  # 2. Set 0 to taxa count that lesser than 1% of total sequencing dept
  group_by(sample) %>% 
  mutate(count2 = if_else(count < 0.01 * sum(count), 0, count)) %>%
  # 3. Remove rare taxa, the one that found lesser that 1 % of total sample
  group_by(asv) %>% 
  mutate(rare = if_else(count2 != 0, 1, 0)) %>% 
  filter(sum(rare) >= 0.01*n_distinct(sample)) %>%
  # 4. Remove contamination 
  ungroup() %>% 
  filter(taxa != "g__Turneriella" & taxa != "o__Chloroplast")



# Match with metabolite classification from HMDB

curated_df <- read.csv("HMDB_chemicalClassification/final_curate_metabolite.csv")
original_df <- read.csv("HMDB_chemicalClassification/mathced_mataboliteName.csv")

comb_df <- cbind(curated_df[1:327, ], original_df$Query)
comb_df <- comb_df %>% select(-c(Query,Closest_Match)) %>% dplyr::rename(metabolite = `original_df$Query`)

taxa_table <- f.table %>% inner_join(., comb_df, by = "metabolite") 

# manually change broken metabolite names

taxa_table$metabolite <- gsub("\\?-AminoButyricAcid", "Y-AminoButyricAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("N-Acetyl-\\?-DMannosamine", "N-Acetyl-ß-DMannosamine", taxa_table$metabolite)
taxa_table$metabolite <- gsub("\\?-Phenylethyl-amine", "ß-Phenylethyl-amine", taxa_table$metabolite)
taxa_table$metabolite <- gsub("D,L-\\?-Amino-NButyricAcid", "D,L-a-Amino-NButyricAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("\\?-Amino-NButyricAcid", "Y-Amino-NButyricAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("\\?-Amino-NCaproicAcid", "ε-Amino-NCaproicAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("D,L-\\?-Amino-CaprylicAcid", "D,L-a-Amino-CaprylicAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("\\?-Amino-NValericAcid", "δ-Amino-NValericAcid", taxa_table$metabolite)
taxa_table$metabolite <- gsub("D,L-\\?-GlycerolPhosphate", "D,L-a-GlycerolPhosphate", taxa_table$metabolite)

taxa_table$metabolite <- gsub("1-Thio--DGlucose", "1-Thio-ß-DGlucose", taxa_table$metabolite)
taxa_table$metabolite <- gsub("D,L--Glycerol-Phosphate", "D,L-a-Glycerol-Phosphate", taxa_table$metabolite)
taxa_table$metabolite <- gsub("D-GalactonicAcid--Lactone", "D-GalactonicAcid-Y-Lactone", taxa_table$metabolite)
taxa_table$metabolite <- gsub("L-GalactonicAcid--Lactone", "L-GalactonicAcid-Y-Lactone", taxa_table$metabolite)

taxa_table$sub_class <- ifelse(is.na(taxa_table$sub_class), "Other", taxa_table$sub_class)

taxa_table <- taxa_table %>% 
  mutate(plate.x = case_when(
    str_detect(Plate, "PM1")  ~ "PM1",
    str_detect(Plate, "PM2A") ~ "PM2A",
    str_detect(Plate, "PM3B") ~ "PM3B",
    str_detect(Plate, "PM4A") ~ "PM4A",
    TRUE                      ~ "Other")) %>% 
  group_by(sample) %>% 
  mutate(ra = count/sum(count))

write.csv(taxa_table, "Filtered_taxa_withPlate_chemTaxa.csv")

